# Generated by Django 5.1.4 on 2025-01-06 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0002_remove_employeereview_review_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeereview',
            name='review_month',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
