# Generated by Django 5.1.4 on 2025-01-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0003_employeereview_review_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeereview',
            name='review_month',
            field=models.DateField(),
        ),
    ]
