# Generated by Django 5.1.4 on 2025-01-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviewapp', '0005_delete_employeereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('emp_id', models.CharField(max_length=50)),
                ('developer_name', models.CharField(max_length=100)),
                ('team_leader', models.CharField(blank=True, max_length=100, null=True)),
                ('project_manager', models.CharField(blank=True, max_length=100, null=True)),
                ('review_month', models.DateField()),
                ('delivery_timelines', models.IntegerField()),
                ('utilization_productivity', models.IntegerField()),
                ('technology_understanding', models.IntegerField()),
                ('attitude_responsibility', models.IntegerField()),
                ('code_quality', models.IntegerField()),
                ('communication_skills', models.IntegerField()),
                ('glacier_process_alignment', models.IntegerField()),
                ('bugs_iterations', models.IntegerField()),
                ('attendance_working_hours', models.IntegerField()),
                ('outstanding_performance', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employee_review',
            },
        ),
    ]
