# Generated by Django 5.1.4 on 2025-01-06 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0006_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeereview',
            old_name='attendance_working_hours',
            new_name='attendance',
        ),
        migrations.RenameField(
            model_name='employeereview',
            old_name='attitude_responsibility',
            new_name='attitude',
        ),
        migrations.RenameField(
            model_name='employeereview',
            old_name='bugs_iterations',
            new_name='bugs',
        ),
        migrations.RenameField(
            model_name='employeereview',
            old_name='communication_skills',
            new_name='communication',
        ),
        migrations.RenameField(
            model_name='employeereview',
            old_name='glacier_process_alignment',
            new_name='glacier_process',
        ),
        migrations.RenameField(
            model_name='employeereview',
            old_name='outstanding_performance',
            new_name='outstanding',
        ),
        migrations.RenameField(
            model_name='employeereview',
            old_name='technology_understanding',
            new_name='technology',
        ),
        migrations.RenameField(
            model_name='employeereview',
            old_name='utilization_productivity',
            new_name='utilization',
        ),
    ]
